org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21.1
loader_version=0.16.14
fabric_version=0.116.17+1.21.1

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=hallmark
mod_name=Hallmark
mod_version=1.0.0
mod_license=MIT
mod_authors=AlabasterLeking
mod_description=A mod about minting currency!
maven_group=alabaster.hallmark
archives_base_name=hallmark
